apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  labels:
    app: mywebsite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite-container
        image: 123456789012.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
